In [ ]:
import numpy as np

- create
- basic operation
- math operation
- indexing and slicing
- boolean filter

In [ ]:
x = np.array([1,2,3,4,5])
print(x) #it has turned into a array
print(x.shape)

In [ ]:
a=np.array([[1,2,3],[4,5,6]])
print(a)
print(a.shape)

In [ ]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b)


In [ ]:
z = [0,1,2,3,4,5,6,7,8,9]
nz = np.array([z]*10)
print(nz)
print(nz.shape)

- random
- arange
- linspace

In [ ]:
np.random.rand(3,3)

In [ ]:
np.random.randint(-5,6,(5,5)) #5,5 is the shape

In [ ]:
 # start,stop,step ..gives a array of range
np.arange(0,50,.5)

In [ ]:
#start , stop, number_of_item
np.linspace(0,50,50)

array attributes
- shape
- dtype
- ndim
- size

basic operation
- sum
- mean
- min
- max
- std
- reshape
- transpose
- flatten

In [ ]:
x.dtype

In [ ]:
x =np.random.rand(3,3)
x.dtype

In [ ]:
x.ndim

In [ ]:
z = np.random.randint(1,5,(3,3,3))
z.ndim # dimension of array

In [ ]:
z.size # total elements in the array

In [ ]:
z.sum()

In [ ]:
a = np.random.rand(2,3)
print(a.sum())
print(a.sum(axis=0)) #column wise sum
print(a.sum(axis=1)) #row wise sum

print(a.mean())
print(a.min())
print(a.max())
print(a.std())
print(a.var())
#all methods can be used with axis

In [ ]:
z = np.random.randint(11,99,(5,5))
print(z)
print('transpose')
print(z.transpose())
# or print(z.T)
print('flatten')
print(z.flatten())

In [ ]:
a = np.random.randint(1,10,(4,5))
print(a)
print(a.reshape(20))
print(a.reshape(5,4))
print(a.reshape(2,10))

In [ ]:
a = np.array([[1,2],[3,4]])
b = np.array([[1,2],[3,4]])
print(a)
print(b)


In [ ]:
print('addition')
print(a+b)
print('substraction')
print(a-b)
print("element wise multiplication")
print(a*b) #element wise multiplication
print("matrix multiplication")
print(a @ b) #matrix multiplication
print("element division")
print(a / b) 
print("matrix multiplication")
print(a.dot(b)) # matrix multiplication


In [ ]:
# when using matrix and scalar
print(a - 10) #broadcasting
print(a + 10)
print(a * 10)
print(a / 10)

In [46]:
# indexing
print(a[0,0])
print(a[-1,-1])#last element

1
4


In [45]:
#slicing
x = np.random.randint(1,10,(5,5))
print(x)

[[1 2 6 8 3]
 [6 8 9 5 6]
 [1 9 8 9 2]
 [9 2 3 5 1]
 [3 6 1 5 2]]


#### syntax of slicing
arr[rowstart :rowstop :rowstep , columnStart :columnStop :columnStep]


In [47]:
print(x[:,0]) #first column
print(x[:,-1]) #last column
print(x[:,:3]) #first 3 column

[1 6 1 9 3]
[3 6 2 1 2]
[[1 2 6]
 [6 8 9]
 [1 9 8]
 [9 2 3]
 [3 6 1]]


In [51]:
print(x[1:4,1:4])

[[8 9 5]
 [9 8 9]
 [2 3 5]]
