1. Write a NumPy program to create an array of 10 zeros.

2. Write a NumPy program to create an array of 10 ones.

3. Write a NumPy program to create a 3x3 matrix with values ranging from 0 to 8.

4. Write a NumPy program to reverse an array (first element becomes the last).

5. Write a NumPy program to extract all odd numbers from an array.

6. Write a NumPy program to compute the sum of all elements, mean, and standard deviation of a given array.

7. Write a NumPy program to create a 5x5 matrix with random values and find the minimum and maximum values.

8. Write a NumPy program to create a 2D array with 1 on the border and 0 inside.

9. Write a NumPy program to multiply two given matrices.

10. Write a NumPy program to find the unique elements of an array.

11. Write a NumPy program to extract the elements in the odd-numbered columns of a 2D array.

12. Write a NumPy program to extract the elements in the even-numbered rows of a 2D array.

13. Write a NumPy program to extract a subarray from a given array. The subarray should include the first 3 rows and the columns from index 1 to 4 (inclusive).

14. Write a NumPy program to reverse the order of elements in each column of a 2D array.

15. Write a NumPy program to create a diagonal matrix from a given 1D array. The elements below the diagonal should be zero, and the elements above the diagonal should be squared.

In [ ]:
import numpy as np

In [ ]:
x = np.array([0] *10)
print(x)

In [ ]:
x = np.array([1] *10)
print(x)

In [ ]:
a = np.random.randint(0,8,(3,3))
a

In [ ]:
a = np.arange(0,8)
a[::-1]

In [ ]:
b = np.arange(20,50,1)
b [(b%2!=0)]

In [ ]:
x = np.arange(80)
print(x.sum())
print(x.mean())
print(x.std())


In [ ]:
y = np.random.randint(0,50,(5,5))
print(y)
print("Maximium value",y.max())
print("Minimium value",y.min())

In [ ]:
x = np.ones((6,7), dtype=int)
x[1:-1,1:-1] = 0
x


In [ ]:
x = np.random.randint(1,20,(5,5))
y = np.random.randint(1,20,(5,5))
print("x: ",x)
print("y: ",y)
print('Element wise multiplication')
print(x * y)
print('Matrix multiplication')
print(x @ y)



In [47]:
y = np.random.randint(1,10,(10,10))
print(y)
print('Odd numbered array:')
y[:,1::2]

[[9 7 2 9 6 6 6 1 8 9]
 [9 7 2 1 4 6 8 3 9 3]
 [3 9 9 9 6 1 4 3 1 5]
 [6 3 9 2 5 3 5 4 6 8]
 [8 7 5 1 8 4 8 7 3 9]
 [3 8 8 6 7 5 4 4 1 6]
 [3 9 3 2 7 6 6 3 1 9]
 [8 6 3 6 9 5 3 4 4 6]
 [8 2 7 9 6 3 9 5 7 3]
 [4 8 1 4 2 8 9 3 9 2]]
Odd numbered array:


array([[7, 9, 6, 1, 9],
       [7, 1, 6, 3, 3],
       [9, 9, 1, 3, 5],
       [3, 2, 3, 4, 8],
       [7, 1, 4, 7, 9],
       [8, 6, 5, 4, 6],
       [9, 2, 6, 3, 9],
       [6, 6, 5, 4, 6],
       [2, 9, 3, 5, 3],
       [8, 4, 8, 3, 2]], dtype=int32)

In [48]:
y = np.random.randint(1,10,(10,10))
print(y)
print('Odd numbered array:')
y[:,0::2]

[[5 6 2 2 1 1 3 5 9 2]
 [7 9 2 7 3 8 3 6 5 2]
 [2 9 8 6 4 5 8 3 9 1]
 [4 9 9 8 3 7 9 3 1 6]
 [9 2 7 4 2 1 6 9 4 7]
 [9 2 9 7 8 7 3 4 9 2]
 [4 3 7 7 9 2 8 7 1 8]
 [8 2 5 2 5 1 7 5 6 4]
 [9 7 5 4 6 7 3 5 6 9]
 [8 8 1 2 2 7 7 8 4 1]]
Odd numbered array:


array([[5, 2, 1, 3, 9],
       [7, 2, 3, 3, 5],
       [2, 8, 4, 8, 9],
       [4, 9, 3, 9, 1],
       [9, 7, 2, 6, 4],
       [9, 9, 8, 3, 9],
       [4, 7, 9, 8, 1],
       [8, 5, 5, 7, 6],
       [9, 5, 6, 3, 6],
       [8, 1, 2, 7, 4]], dtype=int32)

In [54]:
y = np.random.randint(1,10,(5,7))
print(y)
y[:3,1:5]

[[5 5 2 6 3 7 9]
 [7 6 7 2 2 5 4]
 [4 9 2 7 1 5 6]
 [7 6 6 5 9 3 9]
 [6 8 3 2 3 7 4]]


array([[5, 2, 6, 3],
       [6, 7, 2, 2],
       [9, 2, 7, 1]], dtype=int32)

In [55]:
y = np.random.randint(1,10,(5,7))
print(y)
print('reversed elements in each column')
print(y[:,::-1])

[[5 1 9 2 6 4 7]
 [5 7 8 3 4 7 9]
 [3 9 3 3 2 9 6]
 [4 9 3 1 3 3 2]
 [1 1 9 8 6 8 9]]
reversed elements in each column
[[7 4 6 2 9 1 5]
 [9 7 4 3 8 7 5]
 [6 9 2 3 3 9 3]
 [2 3 3 1 3 9 4]
 [9 8 6 8 9 1 1]]


In [59]:
a= [1,2,3,4,5]
np.diag(a)


array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])