1. Write a NumPy program to create an array of 10 zeros.

2. Write a NumPy program to create an array of 10 ones.

3. Write a NumPy program to create a 3x3 matrix with values ranging from 0 to 8.

4. Write a NumPy program to reverse an array (first element becomes the last).

5. Write a NumPy program to extract all odd numbers from an array.

6. Write a NumPy program to compute the sum of all elements, mean, and standard deviation of a given array.

7. Write a NumPy program to create a 5x5 matrix with random values and find the minimum and maximum values.

8. Write a NumPy program to create a 2D array with 1 on the border and 0 inside.

9. Write a NumPy program to multiply two given matrices.

10. Write a NumPy program to find the unique elements of an array.

11. Write a NumPy program to extract the elements in the odd-numbered columns of a 2D array.

12. Write a NumPy program to extract the elements in the even-numbered rows of a 2D array.

13. Write a NumPy program to extract a subarray from a given array. The subarray should include the first 3 rows and the columns from index 1 to 4 (inclusive).

14. Write a NumPy program to reverse the order of elements in each column of a 2D array.

15. Write a NumPy program to create a diagonal matrix from a given 1D array. The elements below the diagonal should be zero, and the elements above the diagonal should be squared.

In [2]:
import numpy as np

In [3]:
x = np.array([0] *10)
print(x)

[0 0 0 0 0 0 0 0 0 0]


In [4]:
x = np.array([1] *10)
print(x)

[1 1 1 1 1 1 1 1 1 1]


In [5]:
a = np.random.randint(0,8,(3,3))
a

array([[4, 1, 3],
       [6, 7, 0],
       [0, 1, 3]], dtype=int32)

In [6]:
a = np.arange(0,8)
a[::-1]

array([7, 6, 5, 4, 3, 2, 1, 0])

In [7]:
b = np.arange(20,50,1)
b [(b%2!=0)]

array([21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49])

In [8]:
x = np.arange(80)
print(x.sum())
print(x.mean())
print(x.std())


3160
39.5
23.092206477510977


In [9]:
y = np.random.randint(0,50,(5,5))
print(y)
print("Maximium value",y.max())
print("Minimium value",y.min())

[[45 33 36 19  1]
 [17  9 39 23  8]
 [25 18 24 35  2]
 [12 19 36 15  5]
 [28  2 36  7 42]]
Maximium value 45
Minimium value 1


In [10]:
x = np.ones((6,7), dtype=int)
x[1:-1,1:-1] = 0
x


array([[1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1]])

In [11]:
x = np.random.randint(1,20,(5,5))
y = np.random.randint(1,20,(5,5))
print("x: ",x)
print("y: ",y)
print('Element wise multiplication')
print(x * y)
print('Matrix multiplication')
print(x @ y)



x:  [[14  2 16  3 14]
 [11  1  1  8  8]
 [18 10 14 10 10]
 [13  6 11  5 17]
 [12 12 14 17 17]]
y:  [[ 2  4  2  4  7]
 [16  3  7  6 15]
 [18  7  8  7  3]
 [19  3  1 14  7]
 [12  3 18 12 17]]
Element wise multiplication
[[ 28   8  32  12  98]
 [176   3   7  48 120]
 [324  70 112  70  30]
 [247  18  11  70 119]
 [144  36 252 204 289]]
Matrix multiplication
[[573 225 425 390 435]
 [304 102 189 265 287]
 [758 260 408 490 558]
 [619 213 467 439 538]
 [995 284 543 660 714]]


In [12]:
y = np.random.randint(1,10,(10,10))
print(y)
print('Odd numbered array:')
y[:,1::2]

[[3 9 5 7 2 5 7 1 1 8]
 [6 4 6 7 4 6 7 5 5 9]
 [2 1 4 8 8 7 9 4 5 1]
 [2 6 2 6 7 1 8 5 6 1]
 [4 8 7 3 8 9 5 8 2 8]
 [1 3 4 8 5 7 7 9 2 5]
 [1 6 7 1 2 3 7 2 7 3]
 [8 5 3 5 8 9 5 8 6 3]
 [4 1 5 5 3 3 3 8 9 7]
 [4 8 6 1 7 5 5 5 6 8]]
Odd numbered array:


array([[9, 7, 5, 1, 8],
       [4, 7, 6, 5, 9],
       [1, 8, 7, 4, 1],
       [6, 6, 1, 5, 1],
       [8, 3, 9, 8, 8],
       [3, 8, 7, 9, 5],
       [6, 1, 3, 2, 3],
       [5, 5, 9, 8, 3],
       [1, 5, 3, 8, 7],
       [8, 1, 5, 5, 8]], dtype=int32)

In [13]:
y = np.random.randint(1,10,(10,10))
print(y)
print('Odd numbered array:')
y[:,0::2]

[[9 9 2 6 4 7 2 9 9 1]
 [5 3 1 2 6 8 1 4 1 9]
 [9 7 1 9 2 9 9 8 2 3]
 [6 2 4 3 1 3 2 2 8 7]
 [4 2 5 9 7 7 9 7 9 4]
 [1 1 7 6 4 7 9 7 2 8]
 [3 5 7 8 7 2 6 1 5 1]
 [6 9 3 7 6 4 2 1 1 5]
 [6 4 1 3 9 5 8 7 2 7]
 [7 7 8 1 5 1 7 7 6 9]]
Odd numbered array:


array([[9, 2, 4, 2, 9],
       [5, 1, 6, 1, 1],
       [9, 1, 2, 9, 2],
       [6, 4, 1, 2, 8],
       [4, 5, 7, 9, 9],
       [1, 7, 4, 9, 2],
       [3, 7, 7, 6, 5],
       [6, 3, 6, 2, 1],
       [6, 1, 9, 8, 2],
       [7, 8, 5, 7, 6]], dtype=int32)

In [14]:
y = np.random.randint(1,10,(5,7))
print(y)
y[:3,1:5]

[[8 6 7 7 5 2 5]
 [5 7 1 3 4 1 5]
 [5 8 7 7 1 5 2]
 [8 2 1 9 3 3 4]
 [4 4 8 2 2 9 8]]


array([[6, 7, 7, 5],
       [7, 1, 3, 4],
       [8, 7, 7, 1]], dtype=int32)

In [15]:
y = np.random.randint(1,10,(5,7))
print(y)
print('reversed elements in each column')
print(y[:,::-1])

[[9 9 5 7 6 7 9]
 [1 5 8 3 8 7 2]
 [8 2 8 3 3 2 6]
 [5 8 3 8 5 9 9]
 [1 7 5 5 8 6 6]]
reversed elements in each column
[[9 7 6 7 5 9 9]
 [2 7 8 3 8 5 1]
 [6 2 3 3 8 2 8]
 [9 9 5 8 3 8 5]
 [6 6 8 5 5 7 1]]


In [16]:
a= [1,2,3,4,5]
np.diag(a)


array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])